repos:
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    -   id: bandit
        args: ["-s", "B101", "-lll"] # -lll for high-severity
-   repo: https://github.com/pyupio/safety
    rev: 3.7.0
    hooks:
    -   id: safety
        name: safety-check-requirements
        files: ^requirements\.txt$
        args: ["check", "--file=requirements.txt", "--bare"]
    -   id: safety
        name: safety-check-config-requirements
        files: ^config/requirements\.txt$
        args: ["check", "--file=config/requirements.txt", "--bare"]
-   repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.77.1
    hooks:
    -   id: trufflehog
