apiVersion: v1
kind: ConfigMap
metadata:
  name: honeypot-config
  namespace: honeypot
data:
  honeypot_config.json: |
    {
        "HONEYPOT_DOMAIN": "example.com",
        "LISTEN_ADDR": "0.0.0.0",
        "LISTEN_PORT": 8053,
        "HEALTH_METRICS_PORT": 8000,
        "REAL_SUBDOMAINS": {
            "www": "93.184.216.34",
            "mail": "203.0.113.10",
            "smtp": "203.0.113.25"
        },
        "FAKE_SUBDOMAINS": {
            "admin": "10.0.1.1",
            "vpn": "10.0.1.2",
            "secure": "10.0.1.3",
            "portal": "10.0.1.4",
            "api": "10.0.1.5"
        }
    }
